# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_btn_plus(object):
    def setupUi(self, btn_plus):
        self.is_equal = False

        btn_plus.setObjectName("btn_plus")
        btn_plus.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(btn_plus)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label.setObjectName("label")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(0, 350, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_0.setObjectName("btn_0")
        self.btn_equl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equl.setGeometry(QtCore.QRect(200, 350, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_equl.setFont(font)
        self.btn_equl.setStyleSheet("background-color: rgb(0, 238, 0);")
        self.btn_equl.setObjectName("btn_equl")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 300, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 300, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 300, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_3.setObjectName("btn_3")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 250, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 250, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_6.setObjectName("btn_6")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 250, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_4.setObjectName("btn_4")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 200, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 200, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_9.setObjectName("btn_9")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 200, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.btn_7.setObjectName("btn_7")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(300, 300, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.btn_div.setObjectName("btn_div")
        self.btn_subt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subt.setGeometry(QtCore.QRect(300, 200, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_subt.setFont(font)
        self.btn_subt.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.btn_subt.setObjectName("btn_subt")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(300, 250, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.btn_mult.setObjectName("btn_mult")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 150, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.pushButton_15.setObjectName("pushButton_15")
        btn_plus.setCentralWidget(self.centralwidget)

        self.retranslateUi(btn_plus)
        QtCore.QMetaObject.connectSlotsByName(btn_plus)

        self.btn_0.clicked.connect(lambda: self.write_number(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.pushButton_15.clicked.connect(lambda: self.write_number(self.pushButton_15.text()))
        self.btn_subt.clicked.connect(lambda: self.write_number(self.btn_subt.text()))
        self.btn_mult.clicked.connect(lambda: self.write_number(self.btn_mult.text()))
        self.btn_div.clicked.connect(lambda: self.write_number(self.btn_div.text()))

        self.btn_equl.clicked.connect(self.results)

    def retranslateUi(self, btn_plus):
        _translate = QtCore.QCoreApplication.translate
        btn_plus.setWindowTitle(_translate("btn_plus", "MainWindow"))
        self.label.setText(_translate("btn_plus", "0"))
        self.btn_0.setText(_translate("btn_plus", "0"))
        self.btn_equl.setText(_translate("btn_plus", "="))
        self.btn_1.setText(_translate("btn_plus", "1"))
        self.btn_2.setText(_translate("btn_plus", "2"))
        self.btn_3.setText(_translate("btn_plus", "3"))
        self.btn_5.setText(_translate("btn_plus", "5"))
        self.btn_6.setText(_translate("btn_plus", "6"))
        self.btn_4.setText(_translate("btn_plus", "4"))
        self.btn_8.setText(_translate("btn_plus", "8"))
        self.btn_9.setText(_translate("btn_plus", "9"))
        self.btn_7.setText(_translate("btn_plus", "7"))
        self.btn_div.setText(_translate("btn_plus", "/"))
        self.btn_subt.setText(_translate("btn_plus", "-"))
        self.btn_mult.setText(_translate("btn_plus", "x"))
        self.pushButton_15.setText(_translate("btn_plus", "+"))


    def write_number(self, number):
        if self.label.text() == "0" or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)

    def results(self):
        if not self.is_equal:
            to_eval = self.label.text().replace("x", "*")
            res = eval(to_eval)
            self.label.setText(f"Результат: {res}")
            self.is_equal = True
        else:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Сейчас это действие выполнить нельзя")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel | QMessageBox.Reset)

            error.buttonClicked.connect(self.popup_action)

            error.exec_()

    def popup_action(self, btn):
        if btn.text() == "Ок":
            print("Ok")
        elif btn.text() == "Reset":
            self.label.setText("0")
            self.is_equal = False


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    btn_plus = QtWidgets.QMainWindow()
    ui = Ui_btn_plus()
    ui.setupUi(btn_plus)
    btn_plus.show()
    sys.exit(app.exec_())
