from PyQt5 import QtCore, QtGui, QtWidgets
from customButtons import NotDraggableButton, FlagButton
from mouseoverWidget import MouseoverWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 142)
        MainWindow.setWindowOpacity(MainWindow.BASE_OPACITY)
        MainWindow.setStyleSheet(f"background-color: rgb({MainWindow.WINDOW_COLOR});")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setWindowIcon(QtGui.QIcon("Icons/main_logo_yellow+blue"))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        MainWindow.setWindowFlags(
            QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.FramelessWindowHint)

        self.centralwidget = MouseoverWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_frame = QtWidgets.QFrame(self.centralwidget)
        self.up_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.up_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.up_frame.setObjectName("up_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.up_frame)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timer_frame = QtWidgets.QFrame(self.up_frame)
        self.timer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timer_frame.setObjectName("timer_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.timer_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timer = QtWidgets.QLabel(self.timer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timer.sizePolicy().hasHeightForWidth())
        self.timer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.timer.setFont(font)
        self.timer.setStyleSheet(f"color: rgb({MainWindow.TEXT_COLOR});")
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setObjectName("timer")
        self.verticalLayout_3.addWidget(self.timer)
        self.verticalLayout_2.addWidget(self.timer_frame, 0, QtCore.Qt.AlignTop)
        self.button_frame = QtWidgets.QFrame(self.up_frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_button = NotDraggableButton(self.button_frame)
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.minimize_button = NotDraggableButton(self.button_frame)
        self.minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/minimize-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon1)
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout.addWidget(self.minimize_button)
        self.pause_button = NotDraggableButton(self.button_frame)
        self.pause_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/play-button-arrowhead.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_button.setIcon(icon2)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.flag_button = FlagButton(self.button_frame)
        self.flag_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/pennant.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flag_button.setIcon(icon3)
        self.flag_button.setObjectName("flag_button")
        self.horizontalLayout.addWidget(self.flag_button)
        self.restart_button = NotDraggableButton(self.button_frame)
        self.restart_button.setAcceptDrops(True)
        self.restart_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restart_button.setIcon(icon4)
        self.restart_button.setObjectName("restart_button")
        self.horizontalLayout.addWidget(self.restart_button)
        self.verticalLayout_2.addWidget(self.button_frame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.up_frame)
        self.bot_frame = QtWidgets.QFrame(self.centralwidget)
        self.bot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bot_frame.setObjectName("bot_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bot_frame)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_frame = QtWidgets.QFrame(self.bot_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.time_label = QtWidgets.QLabel(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet(f"color: rgb({MainWindow.TEXT_COLOR});")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_2.addWidget(self.time_label)
        self.all_label = QtWidgets.QLabel(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_label.sizePolicy().hasHeightForWidth())
        self.all_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.all_label.setFont(font)
        self.all_label.setStyleSheet(f"color: rgb({MainWindow.TEXT_COLOR});")
        self.all_label.setAlignment(QtCore.Qt.AlignCenter)
        self.all_label.setObjectName("all_label")
        self.horizontalLayout_2.addWidget(self.all_label)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.title_frame)
        self.scroll_frame = QtWidgets.QFrame(self.bot_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_frame.sizePolicy().hasHeightForWidth())
        self.scroll_frame.setSizePolicy(sizePolicy)
        self.scroll_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scroll_frame.setObjectName("scroll_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scroll_frame)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.scroll_frame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 265, 157))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.scroll_frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.scroll_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scroll_frame_2.setObjectName("scroll_frame_2")

        self.scrollAreaLayout = QtWidgets.QHBoxLayout(self.scroll_frame_2)
        self.scrollAreaLayout.setObjectName("horizontalLayout_5")

        self.time_layout = QtWidgets.QVBoxLayout()
        self.time_layout.setObjectName("time_layout")
        self.scrollAreaLayout.addLayout(self.time_layout)

        self.all_layout = QtWidgets.QVBoxLayout()
        self.all_layout.setObjectName("all_layout")
        self.scrollAreaLayout.addLayout(self.all_layout)

        self.horizontalLayout_3.addWidget(self.scroll_frame_2)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.scroll_frame)
        self.verticalLayout.addWidget(self.bot_frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.timer.setText(_translate("MainWindow", "0:00:00"))
        self.time_label.setText(_translate("MainWindow", "Время"))
        self.all_label.setText(_translate("MainWindow", "Итого"))
